# Generated by Django 2.2.2 on 2019-06-16 22:12

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestPin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('rank', models.CharField(choices=[('F', 'F'), ('E', 'E'), ('D', 'D'), ('C', 'C'), ('B', 'B'), ('A', 'A'), ('S', 'S')], default='F', max_length=1)),
                ('roles', multiselectfield.db.fields.MultiSelectField(choices=[('Project Manager', 'Project Manager'), ('Client Partner', 'Client Partner'), ('Product Designer', 'Product Designer'), ('Content Strategist', 'Content Strategist'), ('Team Member', 'Team Member'), ('UXR', 'UXR'), ('IA', 'IA'), ('IXD', 'IXD'), ('UI', 'UI')], max_length=92)),
                ('team_size', models.CharField(choices=[('1', '1'), ('2 - 5', '2 - 5'), ('6 - 9', '6 - 9'), ('10 - 14', '10 - 14'), ('15 - 20(max)', '15 - 20(max)')], default='1', max_length=12)),
                ('duration', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='QuestResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deliverables', multiselectfield.db.fields.MultiSelectField(choices=[('Card Sorting', 'Card Sorting'), ('Executive Summary', 'Executive Summary'), ('Information Architecture', 'Information Architecture'), ('Interviews', 'Interviews'), ('Survey', 'Survey'), ('Personas', 'Personas'), ('Recommendations', 'Recommendations'), ('Research Summary', 'Research Summary'), ('UX Map', 'UX Map')], max_length=122)),
                ('questpin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quests.QuestPin')),
            ],
        ),
    ]
